### ISSUE TITLE
Blog数据库设计

### ISSUE THREAD

**Issue by zmrenwu** [djangoStudyTeam/DjangoBlog#2]
此为我分析有道云笔记官方Blog需要展示的数据设计的最基本的数据库结构，并非完善的，比如没有评论，没有User等。我的想法是从简单的开始，做好基本功能，学习相关知识后再逐步迭代拓展。大家有什么意见请在下面评论，评论支持markdown语法。

关系型数据库（我们使用的是MySQL）的基本结构是一张一张的表，每张表代表某个事物，每张有很列，代表这个事物的属性。关于关系型数据库的详细介绍参考[百度百科](http://baike.baidu.com/link?url=JX2CQzuViVEdUEUZB_plkgmBNSiYtzdQFDJVg8rUmhhnrVTSRESLJM6Ivtlh3AiwwfKG54V1lYQboucxjH8JFikJnqpa9t_5TYbDhWNGGtG)。

这里我们设计的是Blog数据库，基本的有两张表，一张用于存储文章，一张存储文章的分类信息，如下图所示：
![image](http://7xq740.com1.z0.glb.clouddn.com/%E6%95%B0%E6%8D%AE%E5%BA%93%E8%AE%BE%E8%AE%A1%E5%9B%BE.png)

这是数据库的底层结构，django对数据库的底层结构进行了封装，设计起来更加简单，以下是django的对数据库结构的代码表现形式，我会逐行解释，如果对django的model不太熟悉的也可以参考以下官方文档：[django模型层概论](https://docs.djangoproject.com/en/1.9/topics/db/models/)。

```
from django.db import models

class Article(models.Model):
    """
    定义用于储存blog文章的表，必须继承自models.Model
    """
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
    )
    
    title = models.CharField('标题',max_length=70)
    ## 文章标题，每一个Field对应数据库的一列，即某个属性。CharField是存储字符        串的。max_length表示最多存储70个字符。
    
    body = models.TextField(‘正文’)
    ## 文章正文，TextField用于存储文本字符串
    
    created_time = models.DateTimeField(‘创建时间’，auto_now_add=True)
    ## 文章创建时间，DateTimeField用于存储时间，设定auto_now_add参数为真，则在        文章被创建时会自动添加创建时间
    
    last_modified_time = models.DateTimeField(‘修改时间’，auto_now=True)
    ## 文章最后一次编辑时间，auto_now=True表示每次修改文章时自动设定修改的时间
    
    status = models.CharField(‘状态’，max_length=1,choices=STATUS_CHOICES)
    ## 文章状态，choices选项会使该field在被渲染成form时被渲染为一个select组件        ，这里我定义了两个状态，一个是Draft（草稿），一个是Published（已发布）
    
    abstract = models.CharField(‘摘要’，max_length=54)
    ## 文章摘要
    
    views = moedels.PositiveIntegerField(‘浏览量’，default=0)
    ## 阅览量，PositiveIntegerField存储非负整数
    
    likes = moedels.PositiveIntegerFieldd(‘点赞数’，default=0)
    ## 点赞数
    
    category = models.ForeignKey('Category',null=True,on_delete=models.SET_NULL)
    ## 文章的分类，ForeignKey即数据库中的外键。外键的定义是：如果数据库中某个        表的列的值是另外一个表的主键。外键定义了一个一对多的关系，这里即一篇文        章对应一个分类，而一个分类下可能有多篇文章。详情参考django官方文档关于ForeinKey的说明：[foreinkey](https://docs.djangoproject.com/en/1.9/topics/db/models/#many-to-one-relationships)，on_delete=models.SET_NULL表示删除某个category后其下所有的Article的外键设为null
    
    def __str__(self):
        return self.title
        

class Category(models.Model):
    """
    分类对应的表，注意它和Article是一对多的关系
    """
    name = models.CharField(max_length=20)
    created_time = models.DateTimeField(auto_now_add=True)
    last_modified_time = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.name
```

**Comment by upczww** [comment]
提出以下几点建议：

1.  定义属性的时候可以加参数verbose_name，该参数的作用是后台显示一个自定义的名字。
比如

`title = models.CharField(max_length=70, verbose_name=u"标题")`
2.  现在的博客都有tag，建议Article增加属性tags:

`tags = models.CharField(max_length=200,null=True,blank=True,verbose_name=u'标签',help_text=u'用逗号分隔')`
3. 可以给Article增加置顶属性：

`is_top = models.BooleanField(default=False,verbose_name=u'置顶')`

暂时想到这些，欢迎大家补充。

**Comment by zmrenwu** [comment]
@upczww 嗯，tag暂时不加了，有分类展示即可。tag在后续的版本中补上。目前第一版完全仿照有道云笔记Blog的页面和布局。

**Comment by fakegit** [comment]
按照wordpress的数据库设计不错，我自己在做，只是精力有限，进度缓慢

**Comment by bushkarl** [comment]
setting.py文件在哪里？

**Comment by bdbai** [comment]
`config` 目录，注意分支。
目前开发过程中数据库使用 SQLite，默认情况下执行迁移操作后，`db.sqlite3` 会出现在你的项目目录下。

Date: Thu, 30 Jun 2016 23:49:12 -0700
