### ISSUE TITLE
如何加入邮件列表

### ISSUE THREAD

**Issue by amoyiki** [djangoStudyTeam/DjangoBlog#31]
> 同时，你也可以加入我们的邮件列表 django_study@groups.163.com ，随时关注我们的动态，我们会将每周的详细开发文档和代码通过邮件列表发出。

然而我好像不懂怎么加入邮件列表，求指教

**Comment by zmrenwu** [comment]
发送邮件到该地址即可


发自 网易邮箱大师
在2016年05月31日 14:22，amoyiki 写道:

同时，你也可以加入我们的邮件列表 django_study@groups.163.com ，随时关注我们的动态，我们会将每周的详细开发文档和代码通过邮件列表发出。

然而我好像不懂怎么加入邮件列表，求指教

**Comment by zmrenwu** [comment]
补充一下，进入邮箱，选通信录，看到邮件列表，点申请加入


发自 网易邮箱大师
在2016年05月31日 14:22，amoyiki 写道:

同时，你也可以加入我们的邮件列表 django_study@groups.163.com ，随时关注我们的动态，我们会将每周的详细开发文档和代码通过邮件列表发出。

然而我好像不懂怎么加入邮件列表，求指教

**Comment by amoyiki** [comment]
@zmrenwu 可以使用Gmail加入吗

**Comment by zmrenwu** [comment]
可以的，你看下gmail的管理页面有没有加入邮件列表的申请按钮


Sent from Mail Master
在2016年05月31日 14:51，amoyiki 写道:

@zmrenwu 可以使用Gmail加入吗

**Comment by chaleaoch** [comment]
@zmrenwu 
可是我并没有在gmail中找到加入邮件列表的申请按钮。另外，发送邮件给*@groups.163.com（使用gmail）被退信。

是否可以求拉？
chaleaoch（at）gmail(dot)com

**Comment by zmrenwu** [comment]
好的，我拉你进来




Sent from Mail Master
在2016年05月31日 22:07，Zhichao,Feng 写道:

@zmrenwu
可是我并没有在gmail中找到加入邮件列表的申请按钮。另外，发送邮件给*@groups.163.com（使用gmail）被退信。

是否可以求拉？
chaleaoch（at）gmail(dot)com

**Comment by amoyiki** [comment]
@zmrenwu 求拉

**Comment by chaleaoch** [comment]
@zmrenwu @amoyiki 
非163邮箱拉不进去的。

**Comment by bdbai** [comment]
顺便问一下最近有通讯吗？我加进来了，但一直没收到过邮件。

**Comment by zmrenwu** [comment]
最近有点忙，教程发布在简书了。


Sent from Mail Master
在2016年06月03日 19:20，bdbai 写道:

顺便问一下最近有通讯吗？我加进来了，但一直没收到过邮件。

**Comment by amoyiki** [comment]
@zmrenwu  ok，那我去注册一个
