### ISSUE TITLE
使用request.POST['xx']取得form数据

### ISSUE THREAD

**Issue by JustT0** [djangoStudyTeam/DjangoBlog#4]
在看官方django教程，遇到个问题，希望可以在这里得到答案。[https://docs.djangoproject.com/en/1.9/intro/tutorial04/](url)
用request.POST['xx']取得表单数据，教程里用try except将它包裹，但是我不知道这个POST方法到底能出现什么异常，哪位高手帮忙解答一下？谢谢

**Comment by zmrenwu** [comment]
@JustT0 
```
try:
    selected_choice = question.choice_set.get(pk=request.POST['choice'])
except (KeyError, Choice.DoesNotExist):
```
这段代码么？两个异常，request.POST['choice']设计到类字典对象取值，因此可能触发KeyError异常，还有就是get方法从数据库中get模型，如果不存在，则会触发DoesNotExist异常。

**Comment by JustT0** [comment]
@zmrenwu 谢谢，dict的取值方式d['xx']调用的是哪个方法啊，我想知道到底是哪个方法会引发KeyError，谢谢。(编程小白，希望谅解。。)

**Comment by JustT0** [comment]
@zmrenwu 多谢，明白了。
