### ISSUE TITLE
feature分支

### ISSUE THREAD

**Issue by JFluo2011** [djangoStudyTeam/DjangoBlog#41]
你们feature会报错吗，为什么我的老是报错
Reverse for 'monthly_archives' with arguments '()' and keyword arguments '{'year': 2016, 'month': '06'}' not found. 0 pattern(s) tried: []

**Comment by zmrenwu** [comment]
feature分支有些代码没有通过测试，因此不能保证能够完全运行，我们接下来会修复这些问题。


Sent from Mail Master
在2016年06月08日 13:47，JFluo 写道:

你们feature会报错吗，为什么我的老是报错
Reverse for 'monthly_archives' with arguments '()' and keyword arguments '{'year': 2016, 'month': '06'}' not found. 0 pattern(s) tried: []

**Comment by JFluo2011** [comment]
额，那现在没办法运行么

**Comment by zmrenwu** [comment]
应该是的


Sent from Mail Master
在2016年06月08日 13:51，JFluo 写道:

额，那现在没办法运行么

**Comment by JFluo2011** [comment]
base.html 
这句有问题：<li class="list-group-item"><a href="{% url 'blog:monthly_archives' year=archiveItem.year month=archiveItem|date:'m' %}">{{ archiveItem|date:'Y年m月' }}</a></li>
暂时注释掉能运行。

**Comment by bdbai** [comment]
@zmrenwu 哪里可以找到测试呢？
