### ISSUE TITLE
为何所有的view都要对article的body用markdown2处理，这样会增加服务器负担吗？

### ISSUE THREAD

**Issue by Andor-Z** [djangoStudyTeam/DjangoBlog#46]
为何views里所有的视图都要对article的body用markdown2处理。
对于那些ListView会用到body吗，是否是应该只要DetailView处理下body就好？

**Comment by zmrenwu** [comment]
嗯，目前只是功能上的实现演示，有待后续的重构和优化。

**Comment by Andor-Z** [comment]
@zmrenwu 本人新手哈，其实我主要想表达的是：对于那些 `ListView` ，如果我将 Markdown 处理部分去掉，对目前的 blog 有影响吗？

**Comment by zmrenwu** [comment]
没有的


Sent from Mail Master
在2016年06月27日 21:07，Andor-Z 写道:

@zmrenwu 本人新手哈，其实我主要想表达的是：对于那些 ListView ，如果我将 Markdown 处理部分去掉，对目前的 blog 有影响吗？

**Comment by Andor-Z** [comment]
@zmrenwu 好的，谢谢了哈
