### ISSUE TITLE
如何加入邮件列表

### ISSUE THREAD

**Issue by lycaste** [djangoStudyTeam/DjangoBlog#47]
我的邮箱403666963@qq.com

**Comment by zmrenwu** [comment]
已邀请

**Comment by magiclyx** [comment]
也加一下我吧: liu.yuxi.canaan@gmail.com 。 找了很多django的blog, 就这个看着漂亮，唯一不适应的就是python3了

**Comment by zmrenwu** [comment]
已邀请 @magiclyx
