### ISSUE TITLE
关于使用models.Manager的一点疑问？

### ISSUE THREAD

**Issue by Andor-Z** [djangoStudyTeam/DjangoBlog#48]
第四周里的文章归档继承Manager写了新的类ArticleManager，在类中写了新函数 archive ，我有点小疑问：

1. archive 函数是否可以在 类Article 内部使用 @classmethod 实现，实现的效果和使用 models.Manager 有什么区别吗？

2. 如果可以使用 @classmethod 实现同样的效果，那使用 models.Manager 的好处是？

谢谢。

**Comment by zmrenwu** [comment]
也是可以的，但是如果方法过多的话显得Model很臃肿，既然django为我们提供了类管理器，就把和数据库操作相关的逻辑移到类管理器中更好。

**Comment by Andor-Z** [comment]
确实，我之前学习Flask的时候，model里的方法写多了，确实很臃肿，找个方法都难找。
谢谢。
