### ISSUE TITLE
如何理解改变article.body,会影响到返回的article_list?

### ISSUE THREAD

**Issue by apprentice1985** [djangoStudyTeam/DjangoBlog#50]
如何理解改变article.body,会影响到返回的article_list?

```
 def get_queryset(self):
        """
        过滤数据，获取所有已发布文章，并且将内容转成markdown形式
        """
        article_list = Article.objects.filter(status='p')
        # 获取数据库中的所有已发布的文章，即filter(过滤)状态为'p'(已发布)的文章。
        for article in article_list:
            article.body = markdown2.markdown(article.body, )
            # 将markdown标记的文本转为html文本
        return article_list
```

**Comment by zmrenwu** [comment]
因为本身body里存储的是markdown原文，现在重新给article.body 赋值了。article.body = markdown2.markdown(article.body, )

**Comment by apprentice1985** [comment]
感谢，改变article.body我理解，可是这个会影响article_list吗？ 比如用'i'替换article。
```
for i in article_list:
            i.body = markdown2.markdown(article.body, )
            # 将markdown标记的文本转为html文本
        return article_list
```

**Comment by zmrenwu** [comment]
不会，i引用的依然是articlelist里的变量。


Sent from Mail Master
在2016年07月05日 16:02，apprentice1985 写道:

感谢，改变article.body我理解，可是这个会影响article_list吗？ 比如用'i'替换article。

for i in article_list:
            i.body = markdown2.markdown(article.body, )
            # 将markdown标记的文本转为html文本
        return article_list
