### ISSUE TITLE
显示markdown是怎么实现的？我有点不明白

### ISSUE THREAD

**Issue by oksola** [djangoStudyTeam/DjangoBlog#58]
我使用markdown2转换了文章内容，在网页上显示的是转换后的（标签也带上了，不是markdown样式）
比如  ###导语  在网页上显示的就是<h3>导语</h3>

**Comment by bdbai** [comment]
有些 markdown 语法有 html 元素直接对应的吧，几号标题就是 h几。

**Comment by zmrenwu** [comment]
@oksola makdown只是一种标记，markdown解析器通过解析这些标记把相应标记转换成html标签。所以解析后文本就变成了html代码。
