### ISSUE TITLE
依赖项少了一个

### ISSUE THREAD

**Issue by fangqian** [djangoStudyTeam/DjangoBlog#59]
我照着这个项目的说明文档安装配置了这个项目，然后在本地运行的时候报了个错，错误信息提示少装了个pytz，requirement.txt里面并没有这个。。。手动装了这个之后就可以了。

**Comment by fangqian** [comment]
settings.py里面的时区是没有改吗？建议改一下

**Comment by bdbai** [comment]
`master` 分支没有，另外两个分支有。

**Comment by zmrenwu** [comment]
@fangqian 嗯，master分支停在了教程的最后一篇代码阶段，最新的分支在blog-tutorial分支，目前实现了很多特性，换了一套非常漂亮的模板，并加入了评论，新浪微博登录等更多功能。因为目前在对其进行重构，本地的分支可能超过远程分支很多提交，我等会把最新的代码同步上来。

**Comment by magiclyx** [comment]
blog-tutorial 分会也会报错。

报的错误是:no such table: accounts_bloguser。 我注意到代码中，没有accounts_bloguser
module的定义。
我尝试不创建管理员账户， 同样会出现数据库表的错误：no such table: blog_article，而且我也没有找到对应module的定义。

2016-08-12 15:24 GMT+08:00 yangxg <notifications@github.com>:

**Comment by zmrenwu** [comment]
@magiclyx 先makemigrations,然后migrate

**Comment by magiclyx** [comment]
试过了，还尝试过删除所有app下的migrations 和 db文件。 重新makemigrations。重新生成的db中并没有错误提示的那几个表。

晚上我在试一下，看看是不是环境问题

**Comment by zmrenwu** [comment]
晚上我同步最新代码后你再试试


Sent from Mail Master
在2016年08月12日 16:57，Yuxi Liu 写道:
试过了，还尝试过删除所有app下的migrations 和 db文件。 重新makemigrations。重新生成的db中并没有错误提示的那几个表。

晚上我在试一下，看看是不是环境问题
