### ISSUE TITLE
entry-content  图片会撑破页面

### ISSUE THREAD

**Issue by faintbear** [djangoStudyTeam/DjangoBlog#60]
添加：

.entry-content img {
    max-width:100%;
}

**Comment by zmrenwu** [comment]
blog-tutorial分支么？是文章详情也里面的图片么？我下载的别人的模板，部分css样式还没有优化。

**Comment by bdbai** [comment]
给图片元素加上`.img-responsive`类就可以。
http://v3.bootcss.com/css/#images-responsive
