### ISSUE TITLE
迁移脚本问题

### ISSUE THREAD

**Issue by magiclyx** [djangoStudyTeam/DjangoBlog#61]
我运行脚本，执行会出错，脚本内容如下：
> find ./ -name 'migrations' | xargs rm -r -f
>find ./ -name '__pycache__' | xargs rm -r -f
>find ./ -name '*.pyc' | xargs rm -f
>rm -f db.sqlite3
>python3 manage.py makemigrations 
>python3 manage.py migrate 
>python3 manage.py createsuperuser

如果直接运行数据库迁移和创建admin账户，是没有问题的。
> python3 manage.py makemigrations 
> python3 manage.py migrate 
> python3 manage.py createsuperuser 

是不是手动改了迁移脚本？
我觉得在开发阶段，没有数据的时候，没有必要依赖迁移脚本。
应该保证使用迁移命令，随时可以配置环境，所有migrations文件都不会被提交

**Comment by bdbai** [comment]
可以贴一下报错内容吗？

**Comment by zmrenwu** [comment]
嗯，谢谢提醒，可能是迁移文件冲突了，我在本地测试没有问题，以后开发阶段把迁移文件移出版本库。

**Comment by magiclyx** [comment]
错误信息是
> django.db.utils.OperationalError: no such table: accounts_bloguser

就是settings中定义的
> AUTH_USER_MODEL = 'accounts.BlogUser'

应该是更改目录导致的。

**Comment by zmrenwu** [comment]
嗯，已经完全调整了项目结构了，请重新 fork，如果本地有数据先把 db.sqlite3 文件复制到别的地方，之后再拷贝回 weblog/database/ 目录下即可。演示地址：http://yangxg.top/ ，具体参考 readme 文件。
