### ISSUE TITLE
迁移数据库执行出故障怎么回事？

### ISSUE THREAD

**Issue by xiaomintongxue** [djangoStudyTeam/DjangoBlog#62]
按照readme一步步来的。安装完成之后，运行下面命令就出错。
python manage.py makemigrations
        python manage.py migrate
如图：
![default](https://cloud.githubusercontent.com/assets/18399572/17703023/c6b1c53c-6402-11e6-87eb-00d30e13a2a3.png)

**Comment by magiclyx** [comment]
@xiaomintongxue 直接运行迁移命令，应该没有问题。

**Comment by xiaomintongxue** [comment]
没有。我是克隆项目到本地。以后卸载我自己之前的配置重新安装readme各种配置，在运行那个迁移就出现图片上的信息，有问题。

**Comment by magiclyx** [comment]
@xiaomintongxue 你的错误信息不全，看不出问题。可以考虑使用virenv 配置一个干净的环境。

**Comment by xiaomintongxue** [comment]
@magiclyx 这个输入命令之后的信息。我重新运行了你看看。
我重新建立一个自己的项目，但是可以运行的。。很奇怪~~有劳指点。
![default](https://cloud.githubusercontent.com/assets/18399572/17737236/abfbc67c-64be-11e6-8245-add5d38c8be3.png)

**Comment by magiclyx** [comment]
@xiaomintongxue 这个是python3.x的环境。 你貌似是用python2.x运行的！

**Comment by xiaomintongxue** [comment]
@magiclyx 我的确实是2.x，崩溃了。。重新卸载安装，配置试试看了只能。。希望没问题

**Comment by zmrenwu** [comment]
嗯，应该是不兼容py2的，最好用py3.4以上版本吧。


Sent from Mail Master
在2016年08月18日 11:47，xiaomintongxue 写道:

@magiclyx 我的确实是2.x，崩溃了。。重新卸载安装，配置试试看了只能。。希望没问题

**Comment by xiaomintongxue** [comment]
@zmrenwu @magiclyx 多谢两位。。我已经改用3.5的了，可以运行成功。接下来继续学习。。非常感谢~~

**Comment by magiclyx** [comment]
这个 issue 可以关了。 希望@zmrenwu尽快修复一下上个issue迁移文件的问题。 主要是我实在找不到原因。。。

**Comment by zmrenwu** [comment]
嗯，已经完全调整了项目结构了，请重新 fork，如果本地有数据先把 db.sqlite3 文件复制到别的地方，之后再拷贝回 weblog/database/ 目录下即可。演示地址：http://yangxg.top/ ，具体参考 readme 文件。
