### ISSUE TITLE
竟然和我Flask做的一模一样的模版

### ISSUE THREAD

**Issue by rui7157** [djangoStudyTeam/DjangoBlog#63]
我也用Flask做了一个，暂时没有买域名http://104.224.177.62

**Comment by zmrenwu** [comment]
哈哈，模板是网上下的。服务器好像无法连接。

**Comment by rui7157** [comment]
![qq 20160904150959](https://cloud.githubusercontent.com/assets/14315092/18235503/370aef5c-734e-11e6-85a4-f4b073f083cf.png)
