### ISSUE TITLE
社区数据库表设计

### ISSUE THREAD

**Issue by zmrenwu** [djangoStudyTeam/DjangoBlog#7]
这是**食肉动物**给出的一个社区数据库设计，涵盖的很完整了。由于目前我们只做用户系统，因此我把和用户相关的一些字段抽离了出来。大家看一下还有没有需要补充的地方：

用户名
邮箱
密码
头像
性别
生日
个人简介
注册时间
注册时IP
最后一次登录时间
最后一次登录IP
个人网站
GitHub主页地址
昵称
所在公司或学校
职位
关注的人
关注他的人

此外还有成就系统，但是设计比较复杂，可以后期再详细设计。

一下是整个社区的完整表设计：
优化的思想：
一、 索引：
我觉得建立索引还是很有必要的。理由如下：
1  建立索引可以加快检索速度，对于论坛读和写的比例相差很大，用户体验当然是读多写少，所以综合考虑还是要用索引，而且是加在常用的读关键字上。
2  索引之所以会降低更新的速度，是因为更新还包括对索引的更新， 但是，我们可能对发帖标题，发帖内容，回复标题，回复内容这4个字段做更新。需要注意的是，这四个字段并不是用来建立表连接的字段，为了优化查询速度我们不会在这四个字段上建立索引，所以我们建立的索引不会影响更新帖子的性能。只要被索引的列（例如回复表的标题ID）不被频繁更新,即使索引所在地行的其它列被频繁update,索引也不会被更新从而产生性能消耗。

二、分割：
1   数据库切分：用户库、主题库、回复库
2   数据表水平切分：用户库1-n、主题库1-n、回复库1-n （比如按时间分）
3   分布式数据库：每台计算机中都有DBMS的一份完整拷贝副本，并具有自己局部的数据库，位于不同地点的许多计算机通过网络互相连接，共同组成一个     完整的、全局的大型数据库。
4   论坛功能可以进行分隔，不同的服务器负责不同的功能
5  用主从数据库，master是写， slave是读
6  把内容与其它信息分开，好处就是可以让每个表的文件最小化,对数据库操作压力会减小，这样保证每张表数据量很小，操作速度会快，也可以在这里使用缓存

下面是用户系统表结构：
以mysql为例，oracle也可。
-- user 用户表
-----------
CREATE TABLE user (
 user_id mediumint(8) NOT NULL AUTO_INCREMENT COMMENT '用户ID',
 group_id mediumint(8) NOT NULL COMMENT '用户组ID',
 user_name varchar(32) NOT NULL COMMENT '用户名',
 user_pwd varchar(32) NOT NULL COMMENT '用户密码',
 user_phone int(12) NOT NULL COMMENT '用户手机号码',
 user_sex varchar(6) NOT NULL COMMENT '用户性别',
 user_qq mediumint(9) NOT NULL COMMENT '用户QQ号码',
 user_email varchar(64) NOT NULL COMMENT '用户EMAIL地址',
 user_address varchar(255) NOT NULL COMMENT '用户地址',
 user_mark mediumint(9) NOT NULL COMMENT '用户积分',
 user_rank_id tinyint(3) NOT NULL COMMENT '用户等级',
 user_last_login_ip varchar(15) NOT NULL COMMENT '用户上一次登录IP地址',
 user_birthday int(13) NOT NULL COMMENT '用户生日',
 user_description varchar(255) NOT NULL COMMENT '自我描述',
 user_image_url varchar(255) NOT NULL COMMENT '用户头像存储路径',
 user_school varchar(255) NOT NULL COMMENT '毕业学校',
 user_register_time int(13) NOT NULL COMMENT '用户注册时间',
 user_register_ip varchar(15) NOT NULL COMMENT '用户注册时IP地址',
 user_last_update_time int(13) NOT NULL COMMENT '用户上次更新博客时间',
 user_weibo varchar(255) NOT NULL COMMENT '用户微博',
 user_blood_type char(3) NOT NULL COMMENT '用户血型',
 user_says varchar(255) NOT NULL COMMENT '用户语录',
 user_lock tinyint(3) NOT NULL COMMENT '是否锁定，0为不锁定，1为锁定',
 user_freeze tinyint(3) NOT NULL COMMENT '是否冻结，0为不冻结，1为冻结',
 user_power varchar(255) NOT NULL COMMENT '拥有权限',
 PRIMARY KEY (user_id), 
 UNIQUE ind_user_name (user_name)
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;

-----------------
-- user_rank 用户权限表
-----------------
CREATE TABLE user_rank (
 rank_id mediumint(5) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
 user_rank_id smallint(5) NOT NULL COMMENT '等级ID',
 rank_mark mediumint(6) NOT NULL COMMENT '等级积分',
 rank_name varchar(32) NOT NULL COMMENT '等级名称',
 PRIMARY KEY (rank_id)
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;

----------------
--user_group 用户组表
----------------
CREATE TABLE user_group (
 g_id tinyint(3) NOT NULL AUTO_INCREMENT COMMENT '自增ID号',
 group_id tinyint(3) NOT NULL COMMENT '用户组ID',
 group_name varchar(20) NOT NULL COMMENT '用户组名',
 group_power varchar(20) NOT NULL COMMENT '用户权限',
 PRIMARY KEY (g_id)
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;
 
 
------------------
-- power_list 功能权限表
------------------
CREATE TABLE power_list (
 p_id int(10) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
 power_id int(10) NOT NULL COMMENT '权限ID',
 power_name varchar(36) NOT NULL COMMENT '权限描述',
 PRIMARY KEY (p_id)
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;
 
-------------------
--friend 好友表 
-------------------
CREATE TABLE friend (
 f_id smallint(5) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
 user_id mediumint(8) NOT NULL COMMENT '用户ID',
 friend_id mediumint(8) NOT NULL COMMENT '好友ID',
 PRIMARY KEY (f_id)
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;

----------------------
--user_attention 用户关注表
----------------------
CREATE TABLE user_attention (
 a_id smallint(5) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
 user_id mediumint(8) NOT NULL COMMENT '用户ID',
 attention_id mediumint(8) NOT NULL COMMENT '关注ID',
 PRIMARY KEY (a_id)
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;

-----------------------
--secret_message 用户私信表
-----------------------
CREATE TABLE secret_message (
 secret_id mediumint(8) NOT NULL AUTO_INCREMENT COMMENT '自增私信ID',
 send_id mediumint(8) NOT NULL COMMENT '发信者ID',
 receive_id mediumint(8) NOT NULL COMMENT '收信者ID',
 message_topic varchar(64) NOT NULL COMMENT '私信标题',
 message_content varchar(255) NOT NULL COMMENT '私信内容',
 PRIMARY KEY (secret_id)
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;
 
------------------------
--system_message 系统通知表
------------------------
CREATE TABLE system_message (
 system_id mediumint(8) NOT NULL AUTO_INCREMENT COMMENT '系统通知ID',
 send_id mediumint(8) NOT NULL COMMENT '接受者ID',
 group_id tinyint(3) NOT NULL COMMENT '用户组ID',
 send_default mediumint(8) NOT NULL COMMENT '1时发送所有用户，0时则不采用',
 system_topic varchar(60) NOT NULL COMMENT '通知内容',
 system_content varchar(255) NOT NULL COMMENT '通知内容',
 PRIMARY KEY (system_id)
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;

--------------------------
--friendly_link 友情链接
--------------------------
CREATE TABLE friendly_link (
 link_id smallint(5) NOT NULL AUTO_INCREMENT COMMENT '友情链接自增ID',
 link_name varchar(60) NOT NULL COMMENT '友情链接名称',
 link_url varchar(255) NOT NULL COMMENT '链接地址',
 link_logo varchar(255) NOT NULL COMMENT 'LOGO图片',
 show_order tinyint(3) NOT NULL COMMENT '在页面显示的顺序',
 PRIMARY KEY (link_id)
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;

--------------------
--stay_message 用户留言表
--------------------
CREATE TABLE stay_message (
 stay_id smallint(5) NOT NULL AUTO_INCREMENT COMMENT '留言表自增ID',
 user_id mediumint(8) NOT NULL COMMENT '用户ID',
 stay_user_id mediumint(8) NOT NULL COMMENT '留言者ID',
 message_content varchar(255) NOT NULL COMMENT '留言内容',
 stay_user_ip varchar(15) NOT NULL COMMENT '留言用户的IP地址',
 message_stay_time int(13) NOT NULL COMMENT '留言时间',
 place varchar(64) NOT NULL COMMENT '地区',
 PRIMARY KEY (stay_id)
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;

------------------------
--visitor 最近访客表
------------------------
CREATE TABLE visitor (
 v_id mediumint(8) NOT NULL AUTO_INCREMENT COMMENT '访客记录ID',
 visitor_id mediumint(8) NOT NULL COMMENT '访客ID',
 visitor_time int(13) NOT NULL COMMENT '来访时间',
 user_id mediumint(8) NOT NULL COMMENT '被访用户ID',
 visitor_ip varchar(15) NOT NULL COMMENT '访客IP地址',
 type_id int(3) NOT NULL COMMENT '访问板块ID',
 where_id mediumint(8) NOT NULL COMMENT '查看某板块的某个子项目，如查看相册板块的第3个相册，该ID对应该相册的ID号',
 PRIMARY KEY (v_id)
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;
 
-------------------------
--shuoshuo 用户心情说说表
-------------------------
CREATE TABLE shuoshuo (
 shuo_id mediumint(8) NOT NULL AUTO_INCREMENT COMMENT '说说记录ID',
 user_id mediumint(8) NOT NULL COMMENT '用户ID',
 shuo_time int(13) NOT NULL DEFAULT 0 COMMENT '发布时间',
 shuo_ip varchar(15) NOT NULL COMMENT '说说发布时的IP地址',
 shuoshuo varchar(255) NOT NULL COMMENT '说说内容',
 type_id tinyint(3) NOT NULL DEFAULT 3 COMMENT '栏目ID,默认为3',
 PRIMARY KEY (shuo_id)
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;

-------------------------
--photo_sort 相片分类表
-------------------------
CREATE TABLE photo_sort (
 sort_img_id mediumint(8) NOT NULL  AUTO_INCREMENT COMMENT '相册ID',
 sort_img_name varchar(20) NOT NULL COMMENT '相册名',
 sort_img_type varchar(20) NOT NULL COMMENT '展示方式 0->仅主人可见,1->输入密码即可查看,2->仅好友能查看,3->回答问题即可查看',
 img_password varchar(32) NOT NULL COMMENT '查看密码',
 user_id mediumint(8) NOT NULL COMMENT '所属用户ID',
 img_sort_question varchar(255) NOT NULL COMMENT '访问问题',
 img_sort_answer varchar(128) NOT NULL COMMENT '访问问题的答案',
 type_id int(3) NOT NULL DEFAULT 1 COMMENT '默认1表示相册板块',
 top_pic_src mediumint(8) NOT NULL COMMENT '封面图片的路径',
 PRIMARY KEY (sort_img_id)
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;
 
-------------------------
--photos 相片表
-------------------------
CREATE TABLE photos (
 photo_id mediumint(8) NOT NULL AUTO_INCREMENT COMMENT '相片ID',
 photo_name varchar(255) NOT NULL COMMENT '相片名称',
 photo_src varchar(255) NOT NULL COMMENT '图片路径',
 photo_description varchar(255) NOT NULL COMMENT '图片描述',
 user_id mediumint(8) NOT NULL COMMENT '所属用户ID',
 sort_id mediumint(8) NOT NULL COMMENT '所属相册ID',
 upload_time int(13) NOT NULL COMMENT '图片上传时间',
 upload_ip varchar(15) NOT NULL COMMENT '图片操作上传IP地址',
 PRIMARY KEY (photo_id) 
) ENGINE=InNodb DEFAULT CHARSET=utf8 ;

**Comment by bdbai** [comment]
建议密码字段不要保存成明文，防止被脱裤以后用户隐私泄露。可以用相对耗时的算法来做验证。
字符集用 utf8mb4 据说可以支持 emoji 字符。
另外用户表还可以再分一下，比如用户名、密码这些和自我描述、血型这些可以分几张表。

**Comment by zmrenwu** [comment]
嗯，密码方面django底层已经帮我们处理了。

**Comment by bdbai** [comment]
@zmrenwu 抱歉没有注意到...
