### ISSUE TITLE
linux 运行Performing system checks...  Killed

### ISSUE THREAD

**Issue by mengqingmeng** [djangoStudyTeam/DjangoBlog#73]
在windows 系统下可以运行，但放在linux上面（centos7）python3 manage.py runserver,就出现Performing system checks...

Killed

运行不起来
是因为我的服务器配置太低吗，我的内存512M

求赐教

**Comment by zmrenwu** [comment]
1.查看一下可用内存是否足够
2. 检查一下 8000 端口是否已经被占用？runserver 默认开启8000端口，或者尝试一下其他端口：
python3 manage.py runserver  8888[或者其它未被占用的端口]

**Comment by mengqingmeng** [comment]
至少需要多少可用内存

**Comment by zmrenwu** [comment]
512M 理论上肯定够的，但看你是否运行了其他进程占用过多内存。

**Comment by mengqingmeng** [comment]
查了一下，我把debug模式关了，解决了
